In [ ]:
# 1 pattern problem
# list comprehension
# lamda , map , reduce ,filter
# numpy pandas theory and practical
# 

In [7]:
# pyramid

#      *
#     ***
#    *****
#   *******
#  *********

# num = 5
# for i in range(0,num):
#     # print (" " * )
#     print ()
#     # print (2*i + 1)


5
6
7
8
9


In [8]:
lst = [1,23,45,67,23,22,12,14]

In [9]:
print (lst)

[1, 23, 45, 67, 23, 22, 12, 14]


In [45]:
# new_list = []
for l in lst:
    print(l*2)
# lst
# [l*2 for l in lst]  

2
46
90
134
46
44
24
28


[1, 23, 45, 67, 23, 22, 12, 14]

In [29]:
# list comprehension
# usage- 
#  when we want to a create new list with ooperations on it
#  single line statements

# squared sum of each element in the list
print (sum([l**2 for l in lst]))
# implement the same using map & lambda
# map is used when we want to apply a function/ operation 
# on each element of the list we use map
print (sum(list(map(lambda x: x**2,lst))))
# implemt the same using reduce 

from functools import reduce
print (reduce(lambda x,y: x + y,lst))

# factorial of a number
# 5
# Find factorial using while loop, for loop
# Write a function to calculate the factorial using function, and lambda function
# Write a program to find the factorial using map and lamda,
# using reduce



8397
8397
207


In [35]:
# Find all the even elements in the list
print (sorted([ l for l in lst if l % 2 == 0 ]))
# even elements as it is and odd elements /10
print (sorted([ l if l % 2 == 0 else l/10 for l in lst  ]))



[12, 14, 22]
[0.1, 2.3, 2.3, 4.5, 6.7, 12, 14, 22]


In [62]:
# Find all of the numbers from 1-1000 that are divisible by 7
# Find all of the numbers from 1-1000 that have a 3 in them else write not three
# Count the number of spaces in a string

[vals for vals in list(range(1,1000)) if vals%7 ==0]

# [vals if '3' in str(vals) else "not three" for vals in list(range(1,1000))]

str_test = "this is a test string to check for the count of spaces"
# lst.count(' ')
len([s for s in str_test if s==' '])
print (sum([1 if s==' ' else 0 for s in str_test ]))
print (sum([True if s==' ' else False for s in str_test ]))
# we can also use filter onto the iterator

11
11


In [64]:
import numpy as np

In [66]:
np,type(np)

(<module 'numpy' from '/opt/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>,
 module)

In [133]:
# numpy

# creation
    # creation from list
numpy_arr = np.array([1,2,3,4,5,6,7,8,9,10])
print (numpy_arr,type(numpy_arr))
    # creation from random numbers
print (np.random.rand(12))
print (np.random.randint(1,20,10))
    # creation lin_space,ones,zeros
    # Arranging the array
    # numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)
print (np.arange(1,12,2))
# Analytical functions
# Mean, Median, mode
print (np.mean(numpy_arr))
print (np.median(numpy_arr))
print (np.max(numpy_arr))
print (np.min(numpy_arr))
# slicing in numpy array
numpy_arr[4:7]
numpy_arr[7:4:-1]
# numpy_arr[1:4]

#accessing of nupy array is also same as list
numpy_arr[4]
# creation of n dimensional ndarray
numpy_arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (numpy_arr_2d)
# acessing of 2d array
# find the second element from the second row
print (numpy_arr_2d[1][1] )
# Dot product
# shape and reshape

# sqrt
np.sqrt(25)
# square
np.square(3)

# zeros generate
np.zeros(10)
# np.ones()
np.ones(10)
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)[source]
np.linspace(1,15,5)
# mathematics dot product
np.dot(numpy_arr_2d[0],numpy_arr_2d[0])
# shape and reshape

print (np.shape(numpy_arr),np.shape(numpy_arr_2d))

print ("reshape the array/flatten the array",np.reshape(numpy_arr_2d,(9,)))
print (np.shape(np.array([[4],[5]])),[[4],[5]])





[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
[0.72495985 0.18083243 0.60114776 0.14784403 0.8509391  0.23946315
 0.88611063 0.25807069 0.43725945 0.07402191 0.66505698 0.93383255]
[17 19 15  2 19  6 14 15  8 10]
[ 1  3  5  7  9 11]
5.5
5.5
10
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
(10,) (3, 3)
reshape the array/flatten the array [1 2 3 4 5 6 7 8 9]
(2, 1) [[4], [5]]


In [149]:
print (numpy_arr_2d)
# this is converting the array shape in to a 1* 9 dimension array
print ("reshape the array/flatten the array",np.reshape(numpy_arr_2d,(9)))
new_arr = np.reshape(numpy_arr_2d,(9))
print (new_arr)
print (np.reshape(new_arr,(3,3)))
# for cases with not possible shapes with the current list it would give an error
print (np.reshape(new_arr[:-1],(4,2)))
# ndim would return the dimension of the array
print (f'1d-array:{numpy_arr} , 2d-array: {numpy_arr_2d}, 3d-array: {[[[1,1,2]]]}')
print (np.ndim(numpy_arr_2d),np.ndim(numpy_arr),np.ndim([[[1,1,2]]]))







# Steps for preparation of the data
# for any operation on a matrix:
# find the dimension of the array: using ndim
# if needed reshape the data based on your requirement
# apply intented operation on the array

# If we are converting the array into dataframes, for ML models,

[[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape the array/flatten the array [1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
1d-array:[ 1  2  3  4  5  6  7  8  9 10] , 2d-array: [[1 2 3]
 [4 5 6]
 [7 8 9]], 3d-array: [[[1, 1, 2]]]
2 1 3
[[ 1  3  4]
 [ 6  6  7]
 [ 8 12 13]]


In [175]:
# ndim explaination for differnt dimension array
array_1d = [1,2,3,4,5,6,7,8,9]
print ("This is 1d array",array_1d)
print ("the dimension of this array is :",np.ndim(array_1d))
# convert this into 3 x 3
array_2d = np.reshape(array_1d,(3,3))
print ("This is 2d array",array_2d)
print ("the dimension of this array is :",np.ndim(array_2d))
array_3d = np.reshape(array_1d[:-1],(2,2,2))
print ("This is 3d array",array_3d)
print ("the dimension of this array is :",np.ndim(array_3d))
print("\n\n\n\n")


This is 1d array [1, 2, 3, 4, 5, 6, 7, 8, 9]
the dimension of this array is : 1
This is 2d array [[1 2 3]
 [4 5 6]
 [7 8 9]]
the dimension of this array is : 2
This is 3d array [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
the dimension of this array is : 3







In [171]:
print (f'length of the total array: {len(array_3d)} \n array first element {array_3d[0]}\t array second element {array_3d[1]} ,{array_3d[0][0]},{array_3d[0][0][0]}')

length of the total array: 2 
 array first element [[1 3]
 [4 6]]	 array second element [[ 6  7]
 [ 8 12]] ,[1 3],1


In [173]:
print (array_3d[0],np.ndim(array_3d[0]),np.shape(array_3d[0]))

[[1 3]
 [4 6]] 2 (2, 2)


In [174]:
print (array_3d[0][0],np.ndim(array_3d[0][0]),np.shape(array_3d[0][0]))

[1 3] 1 (2,)


In [ ]:
dimensions
arr.ndim
np.arange()
np.zeros()
np.ones()
np.linspace()
np.random.rand()
np.random.randint()
np.max()
np.min()
np.mean()
median mode
np.dot()
shape and reshape


In [ ]:
# Dictionary question counter
# sorting of the dictionary based on keys and values
# 

In [ ]:

# pandas